---

resources: "resources.yaml"
samples: "samples.tsv"
units: "units.tsv"

default_container: "docker://gmsuppsala/somatic:develop"

reference:
  design_bedfile: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/bed/pool1_pool2_nochr_3c.sort.merged.padded20.hg19.210311.met.annotated.bed"

cnvkit_call:
  normal_reference: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/bed/cnvkit_Twist_PoN.cnn"

reference:
  fasta: "reference/WASH7P.fna"
  design_bedfile: "reference/twist_DNA_solid.chr1.annotated.bed"
  
germline_vcf:
  container: "docker://ensemblorg/ensembl-vep:release_99.0"
