$schema: "http://json-schema.org/draft-04/schema#"
description: snakemake configuration file
type: object
properties:
  samples:
    type: string
  units:
    type: string
  resources:
    type: string
    description: Path to resources.yaml file
  default_container:
    type: string
    description: name or path to a default docker/singularity container
  reference:
    type: object
    properties:
      design_bedfile:
        type: string
        description: path to the design bedfile
      fasta:
        type: string
        description: path to fasta reference file
  required:
    - samples
    - units
    - resources
    - default_container

  cnvkit_create_targets:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for cnvkit_create_targets
      container:
        type: string
        description: name or path to docker/singularity container

  cnvkit_create_antitargets:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for cnvkit_create_targets
      container:
        type: string
        description: name or path to docker/singularity container

  cnvkit_create_access:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for cnvkit_create_access
      container:
        type: string
        description: name or path to docker/singularity container

  cnvkit_coverage:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for cnvkit_coverage
      container:
        type: string
        description: name or path to docker/singularity container

  cnvkit_call:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for cnvkit_call
      container:
        type: string
        description: name or path to docker/singularity container
      normal_reference:
        type: string
        description: path to normal reference panel for cnvkit calling

  germline_vcf:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for germline_vcf
      container:
        type: string
        description: name or path to docker/singularity container
      filter:
        type: string
        description: filters used to create the germline vcf file

  cnvkit_call_loh:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for cnvkit_call_loh
      container:
        type: string
        description: name or path to docker/singularity container
