resources: "resources.yaml"
samples: "samples.tsv"
units: "units.tsv"

default_container: "docker://marrip/common:1.1.0"

reference:
  fasta: "reference/WASH7P.fna"
  design_bedfile: "reference/twist_DNA_solid.chr1.annotated.bed"

cnvkit_create_targets:
  container: "docker://gmsuppsala/somatic:develop"

cnvkit_create_antitargets:
  container: "docker://gmsuppsala/somatic:develop"

cnvkit_create_access:
  container: "docker://gmsuppsala/somatic:develop"

cnvkit_coverage:
  container: "docker://gmsuppsala/somatic:develop"

cnvkit_call:
  container: "docker://gmsuppsala/somatic:develop"
  normal_reference: "reference/cnvkit_Twist_PoN_chr1.cnn"
  
germline_vcf:
  container: "docker://ensemblorg/ensembl-vep:release_99.0"
