resources: "resources.yaml"
samples: "samples.tsv"
units: "units.tsv"

default_container: "docker://hydragenetics/common:0.0.1"

reference:
  fasta: "reference/HES45.fna"
  design_bedfile: "reference/twist_DNA_solid.chr1.annotated.bed"
  design_intervals_gatk_cnv: "reference/twist_DNA_solid.HES45.annotated.interval_list"

cnvkit_call:
  container: "docker://gmsuppsala/somatic:develop"
  normal_reference: "reference/cnvkit_Twist_PoN_chr1.cnn"

cnvkit_call_loh:
  container: "docker://gmsuppsala/somatic:develop"

cnvkit_scatter_genome:
  container: "docker://gmsuppsala/somatic:develop"

cnvkit_vcf:
  container: "docker://hydragenetics/common:0.0.1"

germline_vcf:
  container: "docker://ensemblorg/ensembl-vep:release_99.0"

gatk_cnv_collect_read_counts:
  container: "docker://gmsuppsala/somatic:develop"

gatk_cnv_denoise_read_counts:
  container: "docker://gmsuppsala/somatic:develop"
  normal_reference: "reference/twist_DNA_solid.HES45.GATK_cnv.PoN.hdf5"

gatk_cnv_collect_allelic_counts:
  container: "docker://gmsuppsala/somatic:develop"
  SNP_interval: "reference/gnomad_SNP_0.001_target.annotated.interval_list"

gatk_cnv_model_segments:
  container: "docker://gmsuppsala/somatic:develop"

gatk_cnv_call_copy_ratio_segments:
  container: "docker://gmsuppsala/somatic:develop"

gatk_cnv_vcf:
  container: "docker://hydragenetics/common:0.0.1"

svdb_merge:
  container: "docker://hydragenetics/svdb:2.5.0"
  cnv_callers:
    - "cnvkit"
    - "gatk_cnv"
